## Docker commands used to build the application 
# TODO: insert the docker build command
docker build -t techtrends .

## Docker commands used to run the application
# TODO: insert the docker run command
docker run -d  -p 7111:3111 techtrends

## Docker commands used to get the application logs
# TODO: insert the docker logs command 
# I used docker ps to get the name of the container
docker logs relaxed_dhawan

## Logs from the container running the TechTrends application
# TODO: paste logs from the Docker container 
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://172.17.0.2:3111/ (Press CTRL+C to quit)
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:48:11] "GET / HTTP/1.1" 200 -
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:48:11] "GET /static/css/main.css HTTP/1.1" 200 -
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:48:11] "GET /favicon.ico HTTP/1.1" 404 -
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 45, in post
    app.logger.info(f'Article {post.title} retrieved')
AttributeError: 'sqlite3.Row' object has no attribute 'title'
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:49:09] "GET /1 HTTP/1.1" 500 -
ERROR:app:Exception on /2 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 45, in post
    app.logger.info(f'Article {post.title} retrieved')
AttributeError: 'sqlite3.Row' object has no attribute 'title'
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:49:15] "GET /2 HTTP/1.1" 500 -
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:49:19] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:49:19] "GET /static/css/main.css HTTP/1.1" 304 -
INFO:app:Article Test created
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:49:30] "POST /create HTTP/1.1" 302 -
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:49:30] "GET / HTTP/1.1" 200 -
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:49:30] "GET /static/css/main.css HTTP/1.1" 304 -
INFO:app:Health check successful
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:50:55] "GET /healthz HTTP/1.1" 200 -
INFO:app:Metrics request successful
INFO:werkzeug:172.17.0.1 - - [14/Jul/2023 23:51:17] "GET /metrics HTTP/1.1" 200 -
